use crate::{Component, ComponentQuery, Entity, FilterQuery, GetStorage, Query};

/// Trait that defines the core interface for ECS worlds.
///
/// This trait allows writing generic functions that can work with any World
/// generated by the `define_world!` macro. It captures the essential ECS
/// operations: entity management, component operations, and querying.
///
/// # Example
///
/// ```rust,ignore
/// fn run_system<W: WorldTrait>(world: &mut W) {
///     let entity = world.spawn_entity();
///     // ... system logic
/// }
/// ```
pub trait WorldTrait {
    /// Creates a new entity and returns its unique identifier.
    fn spawn_entity(&mut self) -> Entity;

    /// Adds a component to the specified entity.
    ///
    /// If the entity already has a component of this type, it will be replaced.
    fn add_component<C>(&mut self, entity: Entity, component: C)
    where
        C: Component,
        Self: GetStorage<C>;

    /// Removes a component from the specified entity and returns it.
    ///
    /// Returns `None` if the entity doesn't have a component of this type.
    fn remove_component<C>(&mut self, entity: Entity) -> Option<C>
    where
        C: Component,
        Self: GetStorage<C>;

    /// Gets a read-only reference to a component on the specified entity.
    ///
    /// Returns `None` if the entity doesn't have a component of this type.
    fn get_component<C>(&self, entity: Entity) -> Option<&C>
    where
        C: Component,
        Self: GetStorage<C>;

    /// Gets a mutable reference to a component on the specified entity.
    ///
    /// Returns `None` if the entity doesn't have a component of this type.
    fn get_component_mut<C>(&mut self, entity: Entity) -> Option<&mut C>
    where
        C: Component,
        Self: GetStorage<C>;

    /// Query for entities with specific components and optional filters.
    ///
    /// Returns a query that can be passed to systems and iterated over to get
    /// component references for entities that match the filter requirements.
    fn query<C, F>(&mut self) -> Query<'_, C, F, Self>
    where
        C: for<'w> ComponentQuery<'w, Self>,
        F: FilterQuery<Self> + Default,
        Self: Sized;
}

